### ISSUE TITLE
Part 4 Section 8

### ISSUE THREAD

**Issue by chrmsan** [makersacademy/student-directory#11]
Got some good help from @hanrattyjen - but I kinda got stuck implementing an until-loop to my print method. Part 4 says rewrite the each() method (I decided to use each_with_index in my code below. )

However, my problem starts when I add more than 2 names in the students array/hash, and the code below prints each names 2 times per 3 students, 3 times per 4 students, etc... Anyone encountered this problem before? All I want is to have it print the names one time, like it did before I implemented an until-loop....

![skjermbilde 2016-09-15 kl 12 09 18](https://cloud.githubusercontent.com/assets/18068044/18546256/4909f2ba-7b3d-11e6-869a-3919bd3b0869.png)

![skjermbilde 2016-09-15 kl 11 52 14](https://cloud.githubusercontent.com/assets/18068044/18546109/7dacfaa4-7b3c-11e6-9e6a-39419631fd16.png)

![skjermbilde 2016-09-15 kl 11 51 30](https://cloud.githubusercontent.com/assets/18068044/18546118/86c55730-7b3c-11e6-98ae-756be1bb1177.png)

**Comment by hanrattyjen** [comment]
What happens if you remove the each_with_index altogether and just have: 

```
count = 1
until ----  
   puts ""
   count += 1
end
```

**Comment by chrmsan** [comment]
I get an error since I'm not able to call my key values and include them in my string.. i'm tempted to make the students variable into an instance array, but the assignment hasnt asked us to do that just yet...

**Comment by chrmsan** [comment]
moved the issue https://github.com/makersacademy/pre_course/issues/645
