### ISSUE TITLE
8. Exercises(#7)

### ISSUE THREAD

**Issue by tomnunn** [makersacademy/student-directory#12]
Hi Guys,

Having a little difficulty with Exercise No. 7, I have this loop in my `input_students` method. I can't figure out how to set a Default Value for the `:cohort` key within the students array of hashes.

**I've Googled myself out of control and now my brain hurts.**

Any help or advice would be much appreciated 😃 

``` ruby
  # Keep adding a student until break
  loop do
    # Get information about student
    puts "What is their name?"
    name = gets.chomp
    puts "Which cohort are they in? (Press Enter for Default Cohort)" # Can't quite figure out how to set a Default Value
    cohort = gets.chomp.downcase.to_sym
    puts "What is their Occupation?"
    occupancy = gets.chomp

    # Add the student data in hashes to the array
    students << {name: name, cohort: cohort, occupancy: occupancy}
    puts "Now we have #{students.count} Badass Students!"

    # Add another student?
    puts "Add another student (Y/N)"
    break if gets.chomp.downcase == "n"
  end
```

**Comment by hanrattyjen** [comment]
Hi Tom

I did this, which works ok but not exactly what I wanted.  Apologies, the formatting doesn't look right here, I'll work on fixing it!

`puts "Cohort month:"`
 `cohort = gets.chomp`
`# Supplying a default value`
`if cohort.empty?`
    `puts "You haven't entered a value. Please contact us."`
  `cohort = "NO VALUE"`
 `end`

**Comment by tomnunn** [comment]
Thanks for this Jen!

I used your code and done the following:

``` ruby
    # Add default value for cohort
    if cohort.empty? 
      cohort = :september
    end
```

**Comment by alexanderwjrussell** [comment]
Thanks for posting this question and helping with the solution. 

I was struggling to come up with a method of lopping through all the questions and then breaking out on command. You solution is very elegant and readable.

**Comment by tomnunn** [comment]
Glad it helped Alexander :)
