### ISSUE TITLE
Student directory page 8, exercise 8

### ISSUE THREAD

**Issue by roryai** [makersacademy/student-directory#13]
The exercise: "Once you complete the previous exercise, change the way the users are displayed: print them grouped by cohorts. To do this, you'll need to get a list of all existing cohorts (the map() method may be useful but it's not the only option), iterate over it and only print the students from that cohort."

Ruby documentation for .map:

> map { |item| block } → new_ary 
> map → Enumerator
> 
> Invokes the given block once for each element of self.
> Creates a new array containing the values returned by the block.
> See also Enumerable#collect.
> If no block is given, an Enumerator is returned instead.

```
a = [ "a", "b", "c", "d" ]
a.collect { |x| x + "!" }        #=> ["a!", "b!", "c!", "d!"]
a.map.with_index{ |x, i| x * i } #=> ["", "b", "cc", "ddd"]
a                                #=> ["a", "b", "c", "d"]

```

This is the array I'm using:

```
students= [
    {name: "Dr. Hannibal Lecter",            cohort: :november},
    {name: "Darth Vader",                    cohort: :november},
    {name: "Nurse Ratched",                  cohort: :sept},
    {name: "Michael Corleone",               cohort: :november},
    {name: "Alex DeLarge",                   cohort: :sept},
    {name: "The Wicked Witch of the West",   cohort: :november},
    {name: "Terminator",                     cohort: :oct},
    {name: "Freddie Kruger",                 cohort: :november},
    {name: "The Joker",                      cohort: :january},
    {name: "Joffrey Baratheon",              cohort: :november},
    {name: "Norman Bates",                   cohort: :march}
] 
```

Firstly, when the code block below is in the program without being in a method, it returns the values I am looking for as expected.

```
students.map do |hash| if hash[:cohort] == :november
         puts hash[:name]
        end
    end
```

Output: 

```
Dr. Hannibal Lecter
Darth Vader
Michael Corleone
The Wicked Witch of the West
Freddie Kruger
Joffrey Baratheon
```

However, as soon as I put the code block into  method and call that method, things start to go wrong.

I can't explain why the first two code blocks below give their outputs, and wonder whether the last block can be shortened.

This block prints the hash if the :cohort is November, and prints blank lines where the cohort isn't November, interspersed in index order. Why is it returning the blank lines? According to the Ruby documentation, .map "Creates a new array containing the values returned by the block." Surely the if statement only returns the values that are true? Output: 11 lines total.

```
def group students
 students.map do |hash| if hash[:cohort] == :november
         hash[:name]
        end
    end
end

group(students)

```

Output:

```
Dr. Hannibal Lecter
Darth Vader

Michael Corleone

The Wicked Witch of the West

Freddie Kruger

Joffrey Baratheon


```

**This next block gives the correct answers, followed by 11 blank lines (one for each hash in the array).**

The only difference here is the 'puts' on line 3. Output: 17 lines total.

```
def group students
 students.map do |hash| if hash[:cohort] == :november
        puts hash[:name]
        end
    end
end

group(students)
```

Output:

```
Dr. Hannibal Lecter
Darth Vader
Michael Corleone
The Wicked Witch of the West
Freddie Kruger
Joffrey Baratheon













```

**Working code below. Output: 6 lines total.**

```
def group students
    array=[]
 students.map do |hash| if hash[:cohort] == :november
        array << hash[:name]
        end
    end
    array
end

group(students)
```

I feel like lines 2, 4 and 7 (and their respective 'ends' etc) of this code shouldn't be necessary. This is messier than the code blocks above. The first code block is the briefest, how can I modify it to not print the blank lines?

Out of interest, this is how I first wrote the method:

```
def group students
 students.map { |hash| hash[:cohort] == :november}
end

group(students)
```

This is the output:

```
true
true
false
true
false
true
false
true
false
true
false
```

**Comment by roryai** [comment]
I just edited the above entry to reflect the fact that putting the block into a method is what causes the problems.

**Comment by roryai** [comment]
This is the working version from my program, with selection and improved output:

```
def print_selected_cohort students
    selection=gets.chomp
 students.map do |hash| if hash[:cohort] == selection.to_sym
        puts "Name: #{hash[:name].to_s.ljust(32)} Cohort: #{hash[:cohort]}"
        end
    end
end
```

**Comment by MalinnaLeach** [comment]
Are you just looking for an explanation of why you're getting the different results? In your non-method version you are asking it to only puts when the condition is met, hence when it's not, nothing happens and there are no blank lines. The map returns something in theory but the return is not used. The tricky thing with Map is that it is eager to return something from the block you create, unlike each which seems to be a bit more laid back. So when you run a method with map it will want to return the full result of your map block, even if some of the lines are blank. So for what you want to do here, you are probably better off using each instead and that should save you having to shovel into a separate array. Hope that makes sense!

**Comment by roryai** [comment]
Thanks for your response, Malinna. I'm trying to work out what's going on with the aims of both understanding what's going on, and learning how to write the shortest method for what I'm trying to achieve.

The non-method version should still be returning blank lines as puts returns a blank line even if the value is nil.

Why do the blank lines only appear when the block is within a method? Why does adding puts to a method do 2 different things: return the values I'm looking for above 11 blank lines rather than  interspersing the blank lines, and return 6 +11 lines, rather than 11 + 11 lines?

**Comment by MalinnaLeach** [comment]
The non-method is doing the right thing due to your if statement. You are saying - only if this condition is met puts something. So when the condition isn't met, it quite rightly doesn't do anything.

The complication seems to be calling map in a method, which seems to prompt it to return the new array it maps (which gets ignored in the first version). That's the trouble with using map and why it really is best to only use map if you want to use the result it creates, eg.

variable = [1, 2].map {|x| x*2}

If you want variable to equal [2,4]

If you just want to go through every bit of an array and run a block each time that may or may not return a result you really are better off using each! 

Not quite sure about the different results you're seeing from the two method versions, but I'm pretty sure that each will solve your issues! 

Let me know how you get on.

Malinna

**Comment by MalinnaLeach** [comment]
I've just figured it out! In the method version where you are using puts, it is doing what you say so putsing each name that meets the criteria. However, it also want to slot the result of that action into it's map, that it also is desperate to return to you. Because puts is just an action and doesn't intrinsically return anything, it means every line of the map that's created is nothing. Hence, after it puts, it then returns the map to you, which is entirely populated with blank lines. 

Hope that's clear! 

M
