### ISSUE TITLE
CSV Library uninitialized constant CSV (NameError)

### ISSUE THREAD

**Issue by powderham** [makersacademy/student-directory#14]
Hi all,

I am working on exercise 14.7, attempting to use the CSV library to refactor my code. The first example is my code working perfectly with the File class, and the second the error-inducing attempt to refactor with the CSV library. Please note location is a variable set as a string by the user when choosing where to save their students.

```
    File.open(location,"w") do |f|
        @students.each do |student|
            student_data = [student[:name], student[:cohort]]
            csv_line = student_data.join(",")
            f.puts csv_line
        end
    end
```

```
    CSV.open(location) do |csv|
        @students.each do |student|
            student_data = [student[:name], student[:cohort]]
            csv_line = student_data.join(",")
            csv << csv_line
        end
    end
```

I am receiving the below error:
`directory.rb:120:in`save_students': uninitialized constant CSV (NameError)`

On running the code I receive the above error. From what I understand, Ruby throwing an error because CSV has not been declared anywhere, but from the documentation, I can't see any requirement to declare it.

Has anyone else encountered this that can help?

Thanks,
Ed

**Comment by Vanals** [comment]
Did you put "require 'csv'" in your script?

**Comment by ghost** [comment]
require 'csv' 

will do the thing!
