### ISSUE TITLE
Exercise 14

### ISSUE THREAD

**Issue by thegooders** [makersacademy/student-directory#19]
I am trying to refactor the code and play around with Procs while I am at it. 

What I would like to achieve is for the method `save_students` to optionally take the global variable `@ask_filename` (a Proc) as argument. By "optionally", I mean it is not mandatory for `save students` to have this argument passed but if it is passed then the Proc is called within the `save_students` method. 

Furthermore, if `@ask_fllename` is called in the `save_students` method, I think I need `@ask_fllename` to pass the variable `filename` from `@ask_fllename` back to the method `save_students` so that the rest of the code in `save_students` can continue.

I am either simply struggling on the syntax to achieve the intended outcome or I am completely misunderstanding how Procs can and/or do work. I have set out some specific questions, isolated the portion of code that I would like help on, and set out the error message below.

My questions:

(i) Have I created the optional argument correctly?

(ii) It does not seem to like the `call` method on the Proc. Can you explain? This is the error:

`directory.rb:126:in` `save_students': undefined method `call' for [#<Proc:0x007ffde3846f28@directory.rb:6>]:Array `(NoMethodError)`

(iii) How can I pass `filename` from the Proc back to the method `save_students`?

```
@ask_filename = Proc.new do
  puts "What is the name of filename where you like to save the data?"
  filename = STDIN.gets.chomp
end

def save_students(*aProc)
  aProc.call
  # open the file for writing
  file = File.open(filename, "w")
  # iterate over the array of students
  @students.each do |student|
    student_data = [student[:name], student[:cohort], student[:hobby], student[:cob]]
    csv_line = student_data.join(",")
    file.puts csv_line
  end

  puts "---------------------------------------"
  puts "#{@students.count} students have been save to the file: #{filename}..."
  puts "---------------------------------------"

  file.close
end

save_students(@ask_filename)

```

**Comment by schlattk** [comment]
I think you have to pass the proc to the method then it should work - that's what I've done with my ask_filename method. It is called automatically if you pass it as an argument. assume a proc is the same?

**Comment by schlattk** [comment]
btw if the method/proc returns the filename it will be available to save_students

**Comment by thegooders** [comment]
I am not getting you. You will need to be explicit showing me what code goes where. My head is muddled.

**Comment by schlattk** [comment]
pass @ask_filename as an argument to save_students and remove aProc.call

**Comment by schlattk** [comment]
as I said that works with a method

**Comment by thegooders** [comment]
It is not working. The error I am getting is this: `directory.rb:133:in `save_students': undefined local variable or method `filename' for main:Object (NameError)`.

**Comment by thegooders** [comment]
I have been suspecting that the reason I have been getting this error previously is due the local variable `filename` stored in the Proc needs to be passed back to the method `save_students`. I don't know how that happens if indeed it is supposed to happen or I have it all wrong in my head.

**Comment by schlattk** [comment]
ok not sure, how about filename = @ask_filename
I have to read up on procs too..

**Comment by schlattk** [comment]
def ask_file_name
  puts "which file would you like to use"
  filename = STDIN.gets.chomp
end
and passing that as an argument to save_students works in any case

**Comment by thegooders** [comment]
I have tried that it does not work. I I still have the same problem of unwrapping `filename` from the `ask_file_name` method and passing it to `save_students` method.

**Comment by schlattk** [comment]
so you call  save_students like this
 save_students(ask_file_name)
but you define the method like this
 save_students(filename)

**Comment by schlattk** [comment]
ask_file_name returns filename and passes it to save_students

**Comment by thegooders** [comment]
That's exactly how I have done. The only difference is I have defined `save_students` like this:`save_students(*filename)` so that the argument `save_students` takes is an optional one. In fact whether I define the argument optionally or mandatory, neither way works for me.
