### ISSUE TITLE
Ex8.2 from Alice

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/student-directory#23]
```
def print_if_letter(students, letter)
  puts "These student(s)' names begin with the letter #{letter}"
  students.each do |student| # This is an array of hashes
    student.each do |name| # This is a hash
      if student[:name].start_with?(letter)
        puts "#{student[:name]} (#{student[:cohort]} cohort)"
      else
      end
    end
  end
```

**Comment by nikeshashar** [comment]
For some reason, this method prints out the answer twice.

**Comment by kittysquee** [comment]
Is it to do with iterating over it twice?

**Comment by j-rods** [comment]
What is the objective here? I see a loop within a loop, could that maybe cause overcomplication in the output?

**Comment by emmpak** [comment]
Also, when you are iterating over a hash, you can include two variables for the key and value:
 { |key,value| #some code here}. Maybe that can help?

**Comment by ruanodendaal** [comment]
@Alicespyglass like @emmpak mentioned you can use more than one value using the `each_with_index` method. Hopefully that will stop the dupes

**Comment by Alicespyglass** [comment]
@j-rods @emmpak 
- The double loop is to access the hash. In a way:
`students[i][:name].start_with?(letter)`

Because the second do is nested, if I use the same variable (letter), it doesn't like it.

@ruanodendaal - do you mean using `each_with_index` to count the iterations?

**Comment by Alicespyglass** [comment]
Solved it!! There was a reason they got us to use `each_with_index` in the first place.... 

```
def print_if_letter(students, letter)
  #loop through students - each student
  students.each_with_index do |student, i|
    # condition - if name begins with letter
    if students[i][:name].start_with?(letter) # i uses index to loop through array
      #print out name
      puts "#{i + 1}. #{student[:name]} (#{student[:cohort]} cohort)"
      # else end 
    else
    end
  end
end
```
Thanks everyone
