### ISSUE TITLE
Ex 8.5: adding more info 

### ISSUE THREAD

**Issue by exchai93-zz** [makersacademy/student-directory#24]
Hey guys

I've created a separate function for each user input of extra information about the students - hobbies, country of birth and height. However, I am currently listing the information without corresponding to the student.  

Is there a way I can input the new information which corresponds to the particular student?? At the moment I seem to be making a new array each time.

e.g. 
"def country_of_birth
  puts "Please enter the birth country of the students"
  puts "To finish, just hit return twice"
  c_o_b = []
  country = gets.chomp
  while! country.empty? do
    c_o_b << {country: country}
    puts "There are #{country.count} countries"
    country = gets.chomp
  end
  c_o_b
end"

**Comment by freddyfallon** [comment]
I think the key here is that you want to be adding this kind of stuff into the existing input_statements methods. Does that make more sense?
