### ISSUE TITLE
The exercises

### ISSUE THREAD

**Issue by hanrattyjen** [makersacademy/student-directory#9]
Q5 Our code only works with the student name and cohort. Add more information: hobbies, country of birth, height, etc.

 ^^ Wondering if anyone else created new questions and inputs for the new information, or hard-coded some fake answers into the hash?

I did the former but think I've now over-complicated myself when I didn't need to!

**Comment by tomnunn** [comment]
Hey Jen, I created a couple of new questions (Including get input for the student cohort) - which I'm a bit stuck on now (https://github.com/makersacademy/student-directory/issues/12).

**Comment by hanrattyjen** [comment]
Cheers Tom. I did go back and remove all questions apart from name and cohort. It works for now so I'm not going to jinx myself by adding in further questions just yet!
